### ISSUE TITLE
Enhancements for ed25519 and x25519

### ISSUE THREAD

**Issue by semenov-vladyslav** [iotaledger/crypto.rs#103]
## Description

Naming convention in ed25519 and x25519 modules is messy, some convenient methods/traits are not implemented, some functionality is missing.

## Motivation

1. In ed25519 there is no reason to specify *compressed* public key. *Compressed* representation is only used for serialization, uncompressed public key is not used. Why not just public key? Proposal: remove or deprecate names with `compressed` word and introduce corresponding names without it.

2. Unify `xxx_LENGTH` (`ed25519::PUBLIC_KEY_LENGTH`) and `xxx_LEN` (`x25519::PUBLIC_KEY_LEN`). `LEN` just looks ugly when other words are not shortened. Proposal: remove or deprecate `xxx_LEN` and introduce corresponding `xxx_LENGTH`.

3. There's no naming convention for conversions to/from bytes for PublicKey types (eg. `fn from_compressed_bytes(bs: &[u8]) -> Result<ed25519::PublicKey>`). Proposal to implement the following methods and traits:

    - `pub fn to_bytes(&self) -> [u8; PUBLIC_KEY_LENGTH]`
    - `pub fn as_slice(&self) -> &[u8]`
    - `pub fn from_bytes(bytes: [u8; PUBLIC_KEY_LENGTH]) -> Self` or `pub fn try_from_bytes(bytes: [u8; PUBLIC_KEY_LENGTH]) -> Result<Self>`
    - `impl Into<[u8; PUBLIC_KEY_LENGTH]> for &PublicKey`
    - `impl AsRef<[u8]> for PublicKey`
    - `impl From<[u8; PUBLIC_KEY_LENGTH]> for PublicKey` or `impl TryFrom<[u8; PUBLIC_KEY_LENGTH]> for PublicKey`

4. What is the endianness of to/from bytes conversions? Is it a "network" byte order or "native"? RFC 8032 states "All values are coded as octet strings, and integers are coded using little-endian convention", so LE must be the "network" byte order when converting x25519::SecretKey, PublicKeys, ed25519::Signature and x25519::SharedSecret as bytes as they are essentially big integers internally. ed25519::SecretKey is represented as seed bytes and not as a scalar that is derived from the seed, so the byte order here is natural. The old implementation is mixed up: ed25519::SecretKey used `to_le_bytes()`/`from_le_bytes()` which is not correct, and x25519::SecretKey bytes is scalar bytes in LE byte order used `to_bytes()`/`from_bytes()` with `le` infix missing. Also `le` functions suggest there are `be` variants which is confusing. Proposal: agree on "network" byte order which is LE (following RFC 8032), remove or deprecate `to_le_bytes`/`from_le_bytes`, use `to_bytes()`/`from_bytes()`.

5. Wrappers for PublicKey types do not currently implement common traits: `Copy`, `Clone`, `PartialEq`, `Eq`, `Hash`, `Debug`. Proposal: implement these traits. Rationale is trivial for each trait.

6. Generate SecretKey with prng. This allows SecretKeys to be deterministically generated from seed. Proposal: implement `generate_with<R>(rng: &mut R)` constructor.

7. Allow the use of the same secret key for ed25519 and x25519. Rationale: this is helpful as it simplifies key management: instead of two key pairs for signature and DH implementations can use only one `(ed25519::SecretKey,ed25519::PublicKey)` and convert it to x25519 keys when needed. Proposal: `impl From<ed25519::SecretKey/PublicKey> for x25519::SecretKey/PublicKey`.

8. Why `utils::rand::gen`s type is unrestricted? Proposal: Restrict to `Sized + Copy`. Rationale: Sized is obviously required to get size of T at compile time. Copy is needed by types that are copyable with memmove, ie. they are simple and don't contain pointers.

9. Deprecate or just remove/rename/breaking change? If deprecate, then since which version? Proposal: deprecate old names since "1.0.0" version.

10. What should be the convention for conversions for Copy types: `to_bytes(&self)` and `impl From<&PublicKey> for [u8; 32]` vs `to_bytes(self)` and `impl From<PublicKey> for [u8; 32]`? Proposal: follow [this clippy convention](https://rust-lang.github.io/rust-clippy/master/index.html#wrong_self_convention) and use the latter syntax.

## Requirements

Write a list of what you want this feature to do.

1. Address topics above.

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by nothingismagick** [comment]
I understand the rationale here, and think there are good reasons for it, especially with regard to moving to 1.0 - I support (most) of this. 

It will require coordinated revision to stronghold, wallet, iota.rs, identity, and bee - so I think at least one stakeholder from each project should comment here and we should potentially have a deeper discussion especially about points 5 & 9.

@l1h3r @laumair @thibault-martinez @Thoralf-M  @Wollac

**Comment by thibault-martinez** [comment]
I 100% agree with all these changes. This module is definitely messy and confusing atm.
Regarding point 9, I wouldn't even bother deprecating stuff, crypto.rs is 0.6.0 and if we strictly follow semver, we're allowed breaking changes until 1.0.0.

**Comment by semenov-vladyslav** [comment]
About 9. To be fair there's already a breaking change: `from_bytes` has now a different signature, and old `from_bytes` is renamed to `try_from_bytes`. Maybe we should deprecate since 0.7.0 and completely remove in 1.0.0.

About 5. It only deals with PublicKeys. Copy+Clone+Debug is a no-brainer, Eq + Hash allows to use PublicKeys as keys in HashMap.

**Comment by nothingismagick** [comment]
Ok, that makes sense wrt 5. I tend to agree with Thibault too  wrt 9. I just want everyone to be informed and ready to track the changes. I expect it actually to impact identity the most. But like I said, am in favor of your suggestions

**Comment by Wollac** [comment]
I also absolutely agree, the module could desperately need some cleanup! Thanks @semenov-vladyslav for kicking this off!

I do have a question about 4: The RFC-8032 also describes the encoding (e.g. little-endian for scalars or bit-strings with given order,...) we should definitely follow these where defined and for these functions do not use any infixes  `le`. But I guess that was exactly, what you meant :sweat_smile: 
I don't see any drawbacks for 5, but it would improve the handling of crypto.rs.
I don't know how to best handle the versioning/deprecation, @thibault-martinez and @nothingismagick are better candidates to decide this.

**Comment by thibault-martinez** [comment]
As long as we've not hit 1.0, I wouldn't put deprecation flags at all, we're allowed and should do breaking changes now. Libraries users are aware they will potentially have to adapt when using a 0.* version.
This is obviously assuming nothing of crypto.rs leaks outside of the scope of our client libraries and is purely internally used, which is most probably the case.

**Comment by semenov-vladyslav** [comment]
Thanks @Wollac , I clarified 4.

**Comment by l1h3r** [comment]
These are all great changes; the impact to identity should be minimal 🥳 I agree with @thibault-martinez on skipping the deprecation flags since this library is still pre-1.0

**Comment by semenov-vladyslav** [comment]
Removed deprecated stuff, incremented version to 0.7.0 as there are some breaking changes.

**Comment by semenov-vladyslav** [comment]
Is there anything to be done? Can we merge PR and close the issue?
