### ISSUE TITLE
Need help to transfer token from trinity wallet to firely

### ISSUE THREAD

**Issue by problemloading** [iotaledger/crypto.rs#138]
### Discussed in https://github.com/iotaledger/crypto.rs/discussions/28

<div type='discussions-op-text'>

<sup>Originally posted by **nothingismagick** December 11, 2020</sup>

## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

</div>

**Comment by problemloading** [comment]
Need help to transfer my iota token from trinity waller to firelly wallet

**Comment by Thoralf-M** [comment]
Hi @problemloading, crypto.rs is the wrong repository for that
For non ledger migration follow the steps in https://blog.iota.org/firefly-token-migration/
For ledger migration use https://blog.iota.org/firefly-token-migration-guide-for-ledger-users/
If you still have problems you should join the discord linked at the bottom of the page
