### ISSUE TITLE
Add Cipher trait

### ISSUE THREAD

**Issue by l1h3r** [iotaledger/crypto.rs#43]
## Description

crypto.rs should provide a `Cipher` [trait](https://doc.rust-lang.org/rust-by-example/trait.html) to expose a consistent API and make it easier to use multiple algorithms with [generic types](https://doc.rust-lang.org/rust-by-example/generics.html).

## Motivation

This ensures all implementations have a consistent API and allows the following code:

```rust
use crate::ciphers::{aes::Aes256Gcm, chacha::XChaCha20Poly1305, traits::Cipher}

fn generic_encrypt<C: Cipher>(...) -> Result<<C as Cipher>::Tag> {
  C::encrypt(...)
}

let tag = generic_encrypt::<Aes256Gcm>(...)?;
// OR
let tag = generic_encrypt::<XChaCha20Poly1305>(...)?;
```

## Requirements

1. Add a `Cipher` trait, available at `crate::ciphers::traits::Cipher`
2. Provide a `Cipher` implementation for all relevant types in `crate::ciphers`
3. 🎉  Party 🎉 

## Open questions

An example of what this trait might look like is below.

Implementations need to specify:
  - key/nonce/tag lengths (as [typenum](https://docs.rs/typenum/1.12.0/typenum/) values, exposed via `consts`)
  - a custom error type (this example simply ignores the underlying implementation error)
  - a user-friendly name for error messages
  - `encrypt/decrypt` functions with explicitly sized arguments (where appropriate)

The trait would also provide easier-to-use `try_encrypt/try_decrypt` functions that accept rust [slices](https://doc.rust-lang.org/std/primitive.slice.html) as arguments.

Notes: 
  - The conversion in `try_generic_array` is simply a length check/pointer cast - no data is being copied
  - `decrypt` and `try_decrypt` return the length of the plaintext. This is to accommodate implementations that may apply padding.
- It may be worthwhile to add a function to calculate the padding of a plaintext buffer (`fn pad(plaintext: &[u8]) -> usize;`)
  - This is to further accommodate implementations with padding (a default implementation could be provided and just return `0`)

```rust
use aes::cipher::generic_array::{ArrayLength, GenericArray};
use core::convert::TryInto;

pub mod consts {
  pub use aes::cipher::generic_array::typenum::*;
}

pub type Key<T> = GenericArray<u8, T>;

pub type Nonce<T> = GenericArray<u8, T>;

pub type Tag<T> = GenericArray<u8, T>;

pub trait Cipher {
  type KeyLength: ArrayLength<u8>;
  type NonceLength: ArrayLength<u8>;
  type TagLength: ArrayLength<u8>;

  type Error;

  const NAME: &'static str;

  fn encrypt(
    key: &Key<Self::KeyLength>,
    iv: &Nonce<Self::NonceLength>,
    aad: &[u8],
    ptx: &[u8],
    ctx: &mut [u8],
    tag: &mut Tag<Self::TagLength>,
  ) -> Result<(), Self::Error>;

  fn decrypt(
    key: &Key<Self::KeyLength>,
    iv: &Nonce<Self::NonceLength>,
    aad: &[u8],
    tag: &Tag<Self::TagLength>,
    ctx: &[u8],
    ptx: &mut [u8],
  ) -> Result<usize, Self::Error>;

  fn try_encrypt(
    key: &[u8],
    iv: &[u8],
    aad: &[u8],
    ptx: &[u8],
    ctx: &mut [u8],
  ) -> crate::Result<Tag<Self::TagLength>> {
    let key: &Key<Self::KeyLength> = try_generic_array(key)?;
    let iv: &Nonce<Self::NonceLength> = try_generic_array(iv)?;
    let mut tag: Tag<Self::TagLength> = Default::default();

    Self::encrypt(key, iv, aad, ptx, ctx, &mut tag)
      .map_err(|_| crate::Error::CipherError { alg: Self::NAME })?;

    Ok(tag)
  }

  fn try_decrypt(
    key: &[u8],
    iv: &[u8],
    aad: &[u8],
    tag: &[u8],
    ctx: &[u8],
    ptx: &mut [u8],
  ) -> crate::Result<usize> {
    let key: &Key<Self::KeyLength> = try_generic_array(key)?;
    let iv: &Nonce<Self::NonceLength> = try_generic_array(iv)?;
    let tag: &Tag<Self::TagLength> = try_generic_array(tag)?;

    Self::decrypt(key, iv, aad, tag, ctx, ptx)
      .map_err(|_| crate::Error::CipherError { alg: Self::NAME })
  }
}

fn try_generic_array<T>(slice: &[u8]) -> crate::Result<&GenericArray<u8, T>>
where
  T: ArrayLength<u8>,
{
  if slice.len() == T::USIZE {
    Ok(slice.into())
  } else {
    Err(crate::Error::BufferSize {
      needs: T::USIZE,
      has: slice.len(),
    })
  }
}
```

## Are you planning to do it yourself in a pull request?

Yes

**Comment by nothingismagick** [comment]
Is this still on your todo list @l1h3r ?

**Comment by l1h3r** [comment]
> Is this still on your todo list @l1h3r ?

Yeah, I have a branch for it that needs to be updated - https://github.com/iotaledger/crypto.rs/tree/feat/cipher-trait

I don't recall having much left to do, I'll check it out today and try to open a PR

**Comment by nothingismagick** [comment]
Alright, well we want to publish and lock this crate as a beta release so the auditors can review... was going to publish right now, but will wait for your PR.
