### ISSUE TITLE
Cleaner API for Ciphers

### ISSUE THREAD

**Issue by tensor-programming** [iotaledger/crypto.rs#70]
## Description

The current Cipher API is pretty complicated and inconsistent. The heavy use of the `generic_array` library makes type conversion tricky from standard types such as `Vectors` and `Slices`.  Also, when the cypher fails due to a type error, the error messages are not very descriptive; apparently it depends on the type. If you specify a slice without the appropriate length, in some cases you get an error describing that the length is wrong and in other cases you just get a generic panic.  

Example (from stronghold):

```rust
let mut tag = [0u8; Self::TAG_LEN];

...

XChaCha20Poly1305::encrypt(
            ...
            &mut tag
                .try_into()?,
            ...
           )?;
```    

Despite the tag being a mutable slice of size 16 and the `GenericArray` implementing a `TryInto` trait for the conversion (`&mut [u8; 16]`), the tag doesn't get updated by the encryption call. There is no compile time error for this and instead it becomes a runtime error. An appropriate implementation looks more like this:

```rust
let mut tag = vec![0u8; Self::TAG_LEN];

...

XChaCha20Poly1305::encrypt(
            ...
            tag.as_mut_slice()
                .try_into()?,
            ...
           )?;
```

This becomes confusing because the nonce can be written like so without causing the same kind of errors:

```rust
let mut nonce = [0u8; Self::NONCE_LEN];

...

 XChaCha20Poly1305::encrypt(
            ...
            &nonce.try_into()?,
            ...
        )?;
```

Also, the ordering of the parameters for the encryption and decryption functions are inconsistent. The Encryption function looks like this:
```rust
XChaCha20Poly1305::encrypt(
           key,
           nonce,
           associated_data,
           plaintext,
           ciphertext,
           tag,
        )
```

Where as the decryption function looks like this:

```rust
XChaCha20Poly1305::decrypt(
            key,
            nonce,
            associated_data,
            tag,
            ciphertext,
            plaintext
        )
```

The API would be much smoother if the position parameters stayed the same across the two different functions.  The functions `try_encrypt` and `try_decrypt` also contain the same parameter order and the `try_encrypt` function does not allow you to specify a tag. 

## Motivation

The point of this feature is to make the overall cipher API much more user friendly.  As it is right now, its unnecessarily troublesome and unpredictable. Documentation will help with some of this needless complexity, but the type conversion problems will still persist.  Presumably the `try` functions are meant to lessen this complexity, but the lack of a tag on `try_encrypt` makes using it inefficient. 

## Requirements

Write a list of what you want this feature to do.

1. Add more descriptive errors for failure states; mainly length errors and type errors.
2. Fix the ordering of the parameter lists on the methods and the lack of the `tag` parameter on the `try_encrypt` method (or make it clear in the docs that the `try_encrypt` function returns a new tag).
3. Add a better example of these methods in use then what exists in the tests folders at the moment.  Doc testing would be useful for something like this.  

## Are you planning to do it yourself in a pull request?
Yes

**Comment by nothingismagick** [comment]
Thanks @tensor-programming - I think that this is a really, really good point. The inconsistency is one thing, but I have been wondering if would make sense to structure the function's variables. Isn't there a way in rust to do that so it doesn't matter in which order the variables get placed? It would make the ergonomics more user friendly.

In JS you would use an object to wrap your variables, and then when calling the function you call with an object and its irrelevant in which order you call them, but you always name them. This is an example of verbosity being the price to pay for flexibility, but it also has the utility of making the code imminently more legible...

```js
function birthdayToday ({name, date}) {
  if ('string' === typeof name && 'string' === typeof date) {
    return new Date() === date ? `${name}'s birthday is today` : `${name}'s birthday is not today`;
  } else {
    return 'maybe';
  }   
}
// Everyday is my birthday
console.log(birthdayToday({name: 'Daniel', date: new Date()});

// Everyday is still my birthday
console.log(birthdayToday({date: new Date(), name: 'Daniel'});
```

**Comment by tensor-programming** [comment]
No, rust doesn't include any kind of API for "named parameters" aka non-positional parameters; its part of the static nature of the language. The closest thing to optional parameters is to use the `Option` type but you still have to specify all of the arguments in those cases when calling the functions. I guess it is possible with macros but there is no real reason to use macros in this instance.
